version: '3.1'

services:
  mongo:
    container_name: mongodb
    image: mongo:4.4.4-bionic
    restart: always
    ports:
    - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    volumes: 
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./mongodb/db:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_BASICAUTH_USERNAME: expuser
      # ME_CONFIG_BASICAUTH_PASSWORD: exppw
      ME_CONFIG_MONGODB_SERVER: mongodb
  # app:
  #   container_name: tess-node-app
  #   restart: always
  #   build: ./node-app
  #   environment:
  #     DB_USER_ID: dbuser
  #     DB_USER_PW: dbpw
  #     DB_NAME: mydb
  #     DB_SERVER: mongodb
  #     DB_PORT: 27017
  #   ports:
  #     - '3333:3333'
